apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hospital-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    # Force redirect HTTP to HTTPS
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - hospital.local
    secretName: hospital-tls-secret
  rules:
  - host: hospital.local
    http:
      paths:
      - path: /patients(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: patient-service
            port:
              number: 80
      - path: /appointments(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: appointment-service
            port:
              number: 80

