name: CI-CD to Minikube
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ vars.DOCKER_USERNAME }}" --password-stdin

      - name: Build
        run: |
          TAG="v${{ github.run_number }}"
          IMAGE="${{ vars.DOCKER_USERNAME }}/express-img"
          
          docker build -t $IMAGE:$TAG -t $IMAGE:latest .
          
      - name: Scan and Push
        run: |

          docker push $IMAGE:$TAG
          docker push $IMAGE:latest

      - name: Deploy to Minikube
        run: |
          kubectl config use-context dafault
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

